### ISSUE TITLE
Broken links on https://odpi.github.io/egeria-docs/guides/documentation/guide/

### ISSUE THREAD

**Issue by dfcoffin** [odpi/egeria-docs#189]
The following links generate a 404 error:

- [ ] Formatting Standards (https://odpi.github.io/egeria-docs/guides/documentation/guide/formatting) to keep the content of the documentation consistent.
-  The link should be (https://odpi.github.io/egeria-docs/guides/documentation/guide/)

- [ ] Style Guide (https://odpi.github.io/egeria-docs/guides/documentation/guide/style) to keep the documentation clear and understandable.
- The link should be (https://odpi.github.io/egeria-docs/guides/documentation/style/)

**Comment by planetf1** [comment]
Both links looked ok for me -- the page is in guides/documentation/guide.md and refers to 'formatting' -- not sure why it didn't work, but I've changed to an absolute link instead, ditto for the style guide

**Comment by milimetric** [comment]
Seems somewhat related, https://odpi.github.io/egeria-docs/guides/diagnostic/guide/ has a link to a tutorial which points to https://odpi.github.io/egeria-docs/education/tutorials/building-egeria-tutorial/, and that's a 404

**Comment by planetf1** [comment]
Checked these links, and all appear good now, so closing

**Comment by milimetric** [comment]
@planetf1 thanks, but also take a look at the one I mentioned in my comment just above.

**Comment by planetf1** [comment]
@milimetric 
 The guide page you mentioned at no longer exists, the first entry under guide is now http://egeria-project.org/guides/diagnostic/overview/ . That is the page with a link to the 'Building Egeria' tutorial, but that is correct now. These were fixed in the PR mentioned above, commit id was https://github.com/planetf1/egeria-docs/commit/56c425bd42dbc3567de1eb0934f1774972823dcb . Can you still see anything else outstanding?
