### ISSUE TITLE
Install Notes on my M1

### ISSUE THREAD

**Issue by dwolfson** [odpi/egeria-docs#223]
1. when I went to brew install rancher, I found that I had to uninstall a bunch of microk8s stuff from earlier tests (as well as helm) so perhaps suggest that there should be a clean environment?
2. Giving rancher 12gb (of 64) of memory and 4 CPUs (of 10)
3. what do I do after I install Rancher? Do I scroll to the bottom to "Accessing applications in your cluster"? The instructions here seem to be for microk8s..
4. At this point, if I look at the Rancher Desktop and go to the tab for supporting utilities, I see the warning that Rancher has insufficient permission to manipulate /usr/local/bin; in the security panel of preferences I gave Rancher Full Disk Access..it still says it has insufficient permissions. Had to get out the hammer and do "sudo chmod a+w /usr/local/bin"
5. Helm seems to be installed from Rancher?
6. Well even though I did a brew uninstall of helm, the config remains so Egeria charts were already there..
7. What version of helm charts should I be seeing - I see 3.4
8. I see 3.4.1 in devel - should I use those with the M1?
9. trying to install helm chart - helm install --devel egeria/odpi-egeria-lab
Error: INSTALLATION FAILED: must either provide a name or specify --generate-name
  - so I need different syntax... this worked -> helm install --devel lab egeria/odpi-egeria-lab
10. Ok - took several minutes for everything to download and start but looks like everything is started
11. I set up port forwarding for base and jupyter 
12. Ran a couple notebooks and configured servers - all seems to be running

**Comment by planetf1** [comment]
Thanks for the feedback. Very helpful and good to know at least the technical parts are running ok on Apple Silicon/m1/arm64.

I've added some work items to #116, and will summarise back here once I've made more changes

**Comment by planetf1** [comment]
Updates related to many of the comments are now merged. Still will be making final changes before Monday including a check for any breakage after some moving about..

Specifically
1. uninstall isn't covered per-se, if anyone gets stuck we'll handle that through chat initially until it's clear if there's any common patterns
2. I've been testing with 8GB/3CPU which has been workable -- though my mac is struggling (not just due to k8s)
3. Updated in new docs
4. suggested using the rancher installer & added a screenshot on what links to create. A little like 1 it may depend on exactly what was installed before, so chat support may be needed
5. Yes, that's what this flow suggests (in practice you can use your own helm/kubectl if you prefer)
6. Seems harmless
7. New versions released now
8. You needed to until now. The released charts now include the m1 support (and thanks for testing!)
9. I think that was in the chart specific docs. I've corrected any docs there - though still a bit more cleanup to do as recorded in #116
10. Great
11. Great - have improved the docs I hope (and added more info for coco pharma)
12. Super

I think this mostly covers the feedback, so thanks again & will close for now, but if you notice more please let me know!
