### ISSUE TITLE
Wrong slack URL in Egeria-introduction

### ISSUE THREAD

**Issue by dwolfson** [odpi/egeria-docs#488]
The URL says https://slack.lfai.foundation/ rather than https://lfaifoundation.slack.com

the page is https://egeria-project.org/education/egeria-dojo/running-egeria/egeria-introduction/?h=slack#documentation

**Comment by planetf1** [comment]
There are two different slack URLs. The latter (above) can be used to view the channels, but requires one to have a login already.  Since anyone with a login would likely know how to get to slack, the idea of the URL reference was to provide a link where a user could sign-up.

Unfortunately the former link is no longer working (node error). It used to redirect.... have asked on the #general discussion

**Comment by planetf1** [comment]
I've checked with the lf ai team. the correct URL to use that includes invites is https://slack.lfaidata.foundation/

**Comment by planetf1** [comment]
The Url was changed by the LF AI team back just before 11 May 2022 -- we didn't update some/all of the references, so should now search and replace 

https://slack.lfai.foundation -> https://slack.lfaidata.foundation

**Comment by planetf1** [comment]
Ah... See #438 -- I opened an issue at the time, but it hasn't been actioned!

**Comment by planetf1** [comment]
Noticed 1 or two others - addressed by https://github.com/odpi/egeria-docs/pull/644
