### ISSUE TITLE
Process for importing Egeria into Postman as listed in dojo is no longer functioning

### ISSUE THREAD

**Issue by cjjaramillo** [odpi/egeria-docs#696]
The current Egeria dojo documentation section for **"Importing Egeria Postman data"** (https://egeria-project.org/education/tutorials/postman-tutorial/overview/#create-a-new-workspace) lists a process that no longer functions. Postman has made updates (with possible bugs) that prevent users from importing the data the way it is described in the dojo. This will need to be updated for any new users to be able to successfully import Egeria into Postman.

**Comment by planetf1** [comment]
The specific issue is that after selecting Import->Code Repository->Github (and authenticating) is that only organizations the user is a member of are available in the drop down list for 'Organization'.

<img width="448" alt="Screenshot 2023-02-22 at 10 44 36" src="https://user-images.githubusercontent.com/7292002/220597998-4f4da0d9-046f-4264-8f0c-f49cca019083.png">

Previously this could be overtyped with the desired repository, ie 'odpi' but this no longer works. The field is now behaving as a *filter* rather than a seeded entry field

<img width="418" alt="Screenshot 2023-02-22 at 10 44 42" src="https://user-images.githubusercontent.com/7292002/220598027-556e4c64-2714-4847-b5d0-c5fb82fe30df.png">

The documented approach is very useful as postman automatically scans the repo for postman collections & environments.

Note that it WILL work for anyone a member of the odpi organization, but this excludes anyone who has yet to become a contributor. 

This is a change of behaviour. There are some issues open on postman that appear to touch on this. 

The best hope would be that this is a temporary issue, and once reported postman will fix (we may also be able to find which version introduced this issue)

The alternative is to either

A) Import file URL

The user would need to know which URLs to point to - there is a fair list, those could be documented & cut/pasted into postman one at a time

B) Import from file/directory

Similar to above, but requires a git clone.

C) Suggest any user joins the org
The user could request to join odpi, and could have no specific permissions - but users may not want to do this when experimenting

D) Build process creates a composite collection
We could aggregate the required collections together perhaps? To make downlod/install easier?

**Comment by planetf1** [comment]
I opened up a postman issue - https://github.com/postmanlabs/postman-app-support/issues/11767

Suggest we see what they say. Hopefully it's a bug. 
If not, we'll need to redo the docs, and or consider if we want to structure the postman data

**Comment by planetf1** [comment]
Thanks @cjjaramillo for fixing. We can close this now. If I notice a feature status change on the postman issue we can revisit
