### ISSUE TITLE
PR docs build allows the user to press merge when there are breaking errors in the code.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-docs#82]
PR Docs build allows the user to press merge when there are breaking errors in the code. It is therefore possible to think you have merged but you have not and the pr be closed.

**Comment by davidradl** [comment]
The PR build also fails if there are any warnings which there are hundreds. 
The PR build also says that you are up to date but offers you a button to update the branch.

**Comment by planetf1** [comment]
Currently the PR build does more validation such as checking links -- good to know -- but ideally
 a) The PR build should be a mandatory check before allowing merge (this is a setting on the branch rules)
 b) We need to ensure the link check failures --for now-- are 'warnings' since we know there's a lot of work still to do. It should be consistent with the merge build
 c) If we can't easily do b. in the PR check we could ALSO keep the link verification as an optional check (still allowing merge)

**Comment by planetf1** [comment]
PR has been merged, and I have enabled the PR check (the task is called 'build') so this must now pass
